/* Generated by Yosys 0.33 (git sha1 2584903a060) */

(* top =  1  *)
(* src = "inputs/alu_4bit.v:3.1-12.10" *)
module alu_4bit(A, B, Y, clk, Opcode);
  (* src = "inputs/alu_4bit.v:4.13-4.14" *)
  input [3:0] A;
  wire [3:0] A;
  (* src = "inputs/alu_4bit.v:4.15-4.16" *)
  input [3:0] B;
  wire [3:0] B;
  (* src = "inputs/alu_4bit.v:5.13-5.19" *)
  input [1:0] Opcode;
  wire [1:0] Opcode;
  (* src = "inputs/alu_4bit.v:7.14-7.15" *)
  output [7:0] Y;
  wire [7:0] Y;
  (* src = "inputs/alu_4bit.v:6.8-6.11" *)
  input clk;
  wire clk;
  (* src = "inputs/alu_4bit.v:8.12-8.14" *)
  wire [7:0] y1;
  (* src = "inputs/alu_4bit.v:8.15-8.17" *)
  wire [7:0] y2;
  (* src = "inputs/alu_4bit.v:8.18-8.20" *)
  wire [7:0] y3;
  (* src = "inputs/alu_4bit.v:8.21-8.23" *)
  wire [7:0] y4;
  (* module_not_derived = 32'd1 *)
  (* src = "inputs/alu_4bit.v:9.18-9.32" *)
  arithmetic_unit sm1 (
    .x(A),
    .y(B),
    .y1(y1),
    .y2(y2)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "inputs/alu_4bit.v:10.15-10.29" *)
  logical_unit sm2 (
    .x(A),
    .y(B),
    .y3(y3),
    .y4(y4)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "inputs/alu_4bit.v:11.15-11.44" *)
  control_unit sm3 (
    .Opcode(Opcode),
    .Y(Y),
    .clk(clk),
    .y1(y1),
    .y2(y2),
    .y3(y3),
    .y4(y4)
  );
endmodule

(* src = "inputs/alu_4bit.v:14.1-22.10" *)
module arithmetic_unit(x, y, y1, y2);
  wire _00_;
  wire _01_;
  wire _02_;
  wire _03_;
  wire _04_;
  wire _05_;
  wire _06_;
  wire _07_;
  wire _08_;
  wire _09_;
  wire _10_;
  wire _11_;
  wire _12_;
  wire _13_;
  wire _14_;
  wire _15_;
  wire _16_;
  wire _17_;
  wire _18_;
  wire _19_;
  wire _20_;
  wire _21_;
  wire _22_;
  (* src = "inputs/alu_4bit.v:15.13-15.14" *)
  input [3:0] x;
  wire [3:0] x;
  (* src = "inputs/alu_4bit.v:15.15-15.16" *)
  input [3:0] y;
  wire [3:0] y;
  (* src = "inputs/alu_4bit.v:16.17-16.19" *)
  output [7:0] y1;
  wire [7:0] y1;
  (* src = "inputs/alu_4bit.v:16.20-16.22" *)
  output [7:0] y2;
  wire [7:0] y2;
  INV_X1 _23_ (
    .A(y[2]),
    .ZN(_00_)
  );
  INV_X1 _24_ (
    .A(y[3]),
    .ZN(_01_)
  );
  INV_X1 _25_ (
    .A(x[0]),
    .ZN(_02_)
  );
  INV_X1 _26_ (
    .A(x[1]),
    .ZN(_03_)
  );
  NAND2_X1 _27_ (
    .A1(y[0]),
    .A2(x[0]),
    .ZN(_04_)
  );
  XOR2_X1 _28_ (
    .A(y[0]),
    .B(x[0]),
    .Z(y2[0])
  );
  NOR2_X1 _29_ (
    .A1(y[3]),
    .A2(x[3]),
    .ZN(_05_)
  );
  NAND2_X1 _30_ (
    .A1(y[3]),
    .A2(x[3]),
    .ZN(_06_)
  );
  XOR2_X1 _31_ (
    .A(y[3]),
    .B(x[3]),
    .Z(_07_)
  );
  NAND2_X1 _32_ (
    .A1(_00_),
    .A2(x[2]),
    .ZN(_08_)
  );
  XNOR2_X1 _33_ (
    .A(y[2]),
    .B(x[2]),
    .ZN(_09_)
  );
  NOR2_X1 _34_ (
    .A1(y[1]),
    .A2(_03_),
    .ZN(_10_)
  );
  NAND2_X1 _35_ (
    .A1(y[1]),
    .A2(x[1]),
    .ZN(_11_)
  );
  XOR2_X1 _36_ (
    .A(y[1]),
    .B(x[1]),
    .Z(_12_)
  );
  AOI21_X1 _37_ (
    .A(_12_),
    .B1(_02_),
    .B2(y[0]),
    .ZN(_13_)
  );
  NOR2_X1 _38_ (
    .A1(_10_),
    .A2(_13_),
    .ZN(_14_)
  );
  OAI21_X1 _39_ (
    .A(_09_),
    .B1(_10_),
    .B2(_13_),
    .ZN(_15_)
  );
  AOI21_X1 _40_ (
    .A(_07_),
    .B1(_08_),
    .B2(_15_),
    .ZN(_16_)
  );
  AOI21_X1 _41_ (
    .A(_16_),
    .B1(x[3]),
    .B2(_01_),
    .ZN(y2[7])
  );
  NAND3_X1 _42_ (
    .A1(y[0]),
    .A2(x[0]),
    .A3(_12_),
    .ZN(_17_)
  );
  XNOR2_X1 _43_ (
    .A(_04_),
    .B(_12_),
    .ZN(y1[1])
  );
  AOI21_X1 _44_ (
    .A(_09_),
    .B1(_11_),
    .B2(_17_),
    .ZN(_18_)
  );
  AND3_X1 _45_ (
    .A1(_09_),
    .A2(_11_),
    .A3(_17_),
    .ZN(_19_)
  );
  NOR2_X1 _46_ (
    .A1(_18_),
    .A2(_19_),
    .ZN(y1[2])
  );
  AOI21_X1 _47_ (
    .A(_18_),
    .B1(x[2]),
    .B2(y[2]),
    .ZN(_20_)
  );
  XNOR2_X1 _48_ (
    .A(_07_),
    .B(_20_),
    .ZN(y1[3])
  );
  AND3_X1 _49_ (
    .A1(y[0]),
    .A2(_02_),
    .A3(_12_),
    .ZN(_21_)
  );
  NOR2_X1 _50_ (
    .A1(_13_),
    .A2(_21_),
    .ZN(y2[1])
  );
  XNOR2_X1 _51_ (
    .A(_09_),
    .B(_14_),
    .ZN(y2[2])
  );
  AND3_X1 _52_ (
    .A1(_07_),
    .A2(_08_),
    .A3(_15_),
    .ZN(_22_)
  );
  NOR2_X1 _53_ (
    .A1(_16_),
    .A2(_22_),
    .ZN(y2[3])
  );
  OAI21_X1 _54_ (
    .A(_06_),
    .B1(_20_),
    .B2(_05_),
    .ZN(y1[4])
  );
  XOR2_X1 _55_ (
    .A(y[0]),
    .B(x[0]),
    .Z(y1[0])
  );
  assign y1[7:5] = 3'h0;
  assign y2[6:4] = { y2[7], y2[7], y2[7] };
endmodule

(* src = "inputs/alu_4bit.v:31.1-49.10" *)
module control_unit(y1, y2, y3, y4, clk, Opcode, Y);
  (* src = "inputs/alu_4bit.v:36.2-48.5" *)
  wire [7:0] _00_;
  wire _01_;
  wire _02_;
  wire _03_;
  wire _04_;
  wire _05_;
  wire _06_;
  wire _07_;
  wire _08_;
  wire _09_;
  wire _10_;
  wire _11_;
  wire _12_;
  wire _13_;
  wire _14_;
  wire _15_;
  wire _16_;
  wire _17_;
  wire _18_;
  wire _19_;
  wire _20_;
  wire _21_;
  wire _22_;
  wire _23_;
  wire _24_;
  wire _25_;
  wire _26_;
  wire _27_;
  wire _28_;
  wire _29_;
  wire _30_;
  wire _31_;
  wire _32_;
  wire _33_;
  wire _34_;
  wire _35_;
  wire _36_;
  (* src = "inputs/alu_4bit.v:33.13-33.19" *)
  input [1:0] Opcode;
  wire [1:0] Opcode;
  (* src = "inputs/alu_4bit.v:35.17-35.18" *)
  output [7:0] Y;
  wire [7:0] Y;
  (* src = "inputs/alu_4bit.v:34.8-34.11" *)
  input clk;
  wire clk;
  (* src = "inputs/alu_4bit.v:32.13-32.15" *)
  input [7:0] y1;
  wire [7:0] y1;
  (* src = "inputs/alu_4bit.v:32.16-32.18" *)
  input [7:0] y2;
  wire [7:0] y2;
  (* src = "inputs/alu_4bit.v:32.19-32.21" *)
  input [7:0] y3;
  wire [7:0] y3;
  (* src = "inputs/alu_4bit.v:32.22-32.24" *)
  input [7:0] y4;
  wire [7:0] y4;
  INV_X1 _37_ (
    .A(Opcode[0]),
    .ZN(_01_)
  );
  INV_X1 _38_ (
    .A(Opcode[1]),
    .ZN(_02_)
  );
  AND2_X1 _39_ (
    .A1(Opcode[0]),
    .A2(Opcode[1]),
    .ZN(_03_)
  );
  NOR2_X1 _40_ (
    .A1(Opcode[0]),
    .A2(Opcode[1]),
    .ZN(_04_)
  );
  AOI22_X1 _41_ (
    .A1(y4[0]),
    .A2(_03_),
    .B1(_04_),
    .B2(y1[0]),
    .ZN(_05_)
  );
  NAND3_X1 _42_ (
    .A1(_01_),
    .A2(Opcode[1]),
    .A3(y3[0]),
    .ZN(_06_)
  );
  NAND3_X1 _43_ (
    .A1(Opcode[0]),
    .A2(_02_),
    .A3(y2[0]),
    .ZN(_07_)
  );
  NAND3_X1 _44_ (
    .A1(_05_),
    .A2(_06_),
    .A3(_07_),
    .ZN(_00_[0])
  );
  AOI22_X1 _45_ (
    .A1(y4[1]),
    .A2(_03_),
    .B1(_04_),
    .B2(y1[1]),
    .ZN(_08_)
  );
  NAND3_X1 _46_ (
    .A1(_01_),
    .A2(Opcode[1]),
    .A3(y3[1]),
    .ZN(_09_)
  );
  NAND3_X1 _47_ (
    .A1(Opcode[0]),
    .A2(_02_),
    .A3(y2[1]),
    .ZN(_10_)
  );
  NAND3_X1 _48_ (
    .A1(_08_),
    .A2(_09_),
    .A3(_10_),
    .ZN(_00_[1])
  );
  AOI22_X1 _49_ (
    .A1(y4[2]),
    .A2(_03_),
    .B1(_04_),
    .B2(y1[2]),
    .ZN(_11_)
  );
  NAND3_X1 _50_ (
    .A1(_01_),
    .A2(Opcode[1]),
    .A3(y3[2]),
    .ZN(_12_)
  );
  NAND3_X1 _51_ (
    .A1(Opcode[0]),
    .A2(_02_),
    .A3(y2[2]),
    .ZN(_13_)
  );
  NAND3_X1 _52_ (
    .A1(_11_),
    .A2(_12_),
    .A3(_13_),
    .ZN(_00_[2])
  );
  AOI22_X1 _53_ (
    .A1(y4[3]),
    .A2(_03_),
    .B1(_04_),
    .B2(y1[3]),
    .ZN(_14_)
  );
  NAND3_X1 _54_ (
    .A1(_01_),
    .A2(Opcode[1]),
    .A3(y3[3]),
    .ZN(_15_)
  );
  NAND3_X1 _55_ (
    .A1(Opcode[0]),
    .A2(_02_),
    .A3(y2[3]),
    .ZN(_16_)
  );
  NAND3_X1 _56_ (
    .A1(_14_),
    .A2(_15_),
    .A3(_16_),
    .ZN(_00_[3])
  );
  AOI22_X1 _57_ (
    .A1(y4[4]),
    .A2(_03_),
    .B1(_04_),
    .B2(y1[4]),
    .ZN(_17_)
  );
  NAND3_X1 _58_ (
    .A1(_01_),
    .A2(Opcode[1]),
    .A3(y3[4]),
    .ZN(_18_)
  );
  NAND3_X1 _59_ (
    .A1(Opcode[0]),
    .A2(_02_),
    .A3(y2[4]),
    .ZN(_19_)
  );
  NAND3_X1 _60_ (
    .A1(_17_),
    .A2(_18_),
    .A3(_19_),
    .ZN(_00_[4])
  );
  AOI22_X1 _61_ (
    .A1(y4[5]),
    .A2(_03_),
    .B1(_04_),
    .B2(y1[5]),
    .ZN(_20_)
  );
  NAND3_X1 _62_ (
    .A1(_01_),
    .A2(Opcode[1]),
    .A3(y3[5]),
    .ZN(_21_)
  );
  NAND3_X1 _63_ (
    .A1(Opcode[0]),
    .A2(_02_),
    .A3(y2[5]),
    .ZN(_22_)
  );
  NAND3_X1 _64_ (
    .A1(_20_),
    .A2(_21_),
    .A3(_22_),
    .ZN(_00_[5])
  );
  AOI22_X1 _65_ (
    .A1(y4[6]),
    .A2(_03_),
    .B1(_04_),
    .B2(y1[6]),
    .ZN(_23_)
  );
  NAND3_X1 _66_ (
    .A1(_01_),
    .A2(Opcode[1]),
    .A3(y3[6]),
    .ZN(_24_)
  );
  NAND3_X1 _67_ (
    .A1(Opcode[0]),
    .A2(_02_),
    .A3(y2[6]),
    .ZN(_25_)
  );
  NAND3_X1 _68_ (
    .A1(_23_),
    .A2(_24_),
    .A3(_25_),
    .ZN(_00_[6])
  );
  AOI22_X1 _69_ (
    .A1(y4[7]),
    .A2(_03_),
    .B1(_04_),
    .B2(y1[7]),
    .ZN(_26_)
  );
  NAND3_X1 _70_ (
    .A1(_01_),
    .A2(Opcode[1]),
    .A3(y3[7]),
    .ZN(_27_)
  );
  NAND3_X1 _71_ (
    .A1(Opcode[0]),
    .A2(_02_),
    .A3(y2[7]),
    .ZN(_28_)
  );
  NAND3_X1 _72_ (
    .A1(_26_),
    .A2(_27_),
    .A3(_28_),
    .ZN(_00_[7])
  );
  (* src = "inputs/alu_4bit.v:36.2-48.5" *)
  DFF_X1 _73_ (
    .CK(clk),
    .D(_00_[0]),
    .Q(Y[0]),
    .QN(_30_)
  );
  (* src = "inputs/alu_4bit.v:36.2-48.5" *)
  DFF_X1 _74_ (
    .CK(clk),
    .D(_00_[1]),
    .Q(Y[1]),
    .QN(_31_)
  );
  (* src = "inputs/alu_4bit.v:36.2-48.5" *)
  DFF_X1 _75_ (
    .CK(clk),
    .D(_00_[2]),
    .Q(Y[2]),
    .QN(_32_)
  );
  (* src = "inputs/alu_4bit.v:36.2-48.5" *)
  DFF_X1 _76_ (
    .CK(clk),
    .D(_00_[3]),
    .Q(Y[3]),
    .QN(_33_)
  );
  (* src = "inputs/alu_4bit.v:36.2-48.5" *)
  DFF_X1 _77_ (
    .CK(clk),
    .D(_00_[4]),
    .Q(Y[4]),
    .QN(_34_)
  );
  (* src = "inputs/alu_4bit.v:36.2-48.5" *)
  DFF_X1 _78_ (
    .CK(clk),
    .D(_00_[5]),
    .Q(Y[5]),
    .QN(_35_)
  );
  (* src = "inputs/alu_4bit.v:36.2-48.5" *)
  DFF_X1 _79_ (
    .CK(clk),
    .D(_00_[6]),
    .Q(Y[6]),
    .QN(_36_)
  );
  (* src = "inputs/alu_4bit.v:36.2-48.5" *)
  DFF_X1 _80_ (
    .CK(clk),
    .D(_00_[7]),
    .Q(Y[7]),
    .QN(_29_)
  );
endmodule

(* src = "inputs/alu_4bit.v:24.1-29.10" *)
module logical_unit(x, y, y3, y4);
  (* src = "inputs/alu_4bit.v:25.13-25.14" *)
  input [3:0] x;
  wire [3:0] x;
  (* src = "inputs/alu_4bit.v:25.15-25.16" *)
  input [3:0] y;
  wire [3:0] y;
  (* src = "inputs/alu_4bit.v:26.14-26.16" *)
  output [7:0] y3;
  wire [7:0] y3;
  (* src = "inputs/alu_4bit.v:26.17-26.19" *)
  output [7:0] y4;
  wire [7:0] y4;
  AND2_X1 _0_ (
    .A1(x[0]),
    .A2(y[0]),
    .ZN(y3[0])
  );
  AND2_X1 _1_ (
    .A1(x[1]),
    .A2(y[1]),
    .ZN(y3[1])
  );
  AND2_X1 _2_ (
    .A1(x[2]),
    .A2(y[2]),
    .ZN(y3[2])
  );
  AND2_X1 _3_ (
    .A1(x[3]),
    .A2(y[3]),
    .ZN(y3[3])
  );
  XOR2_X1 _4_ (
    .A(x[0]),
    .B(y[0]),
    .Z(y4[0])
  );
  XOR2_X1 _5_ (
    .A(x[1]),
    .B(y[1]),
    .Z(y4[1])
  );
  XOR2_X1 _6_ (
    .A(x[2]),
    .B(y[2]),
    .Z(y4[2])
  );
  XOR2_X1 _7_ (
    .A(x[3]),
    .B(y[3]),
    .Z(y4[3])
  );
  assign y3[7:4] = 4'h0;
  assign y4[7:4] = 4'h0;
endmodule
